name: EdiScan
description: приложение для сканирования кодов

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_share: ^2.0.0
  link_text: ^0.2.0
  url_launcher: ^6.0.20
  image_picker: ^0.8.5
  hexagon: ^0.2.0-nullsafety.1
  mobile_scanner: ^1.1.1
  intl: ^0.17.0
  permission_handler: ^9.0.0
  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.0.1
  floor: ^1.2.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.1.7
  floor_generator: ^1.3.0


  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/icon/back.png
    - assets/photograph.png

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/back.png"
  adaptive_icon_foreground: "assets/icon/icon.png"

